### ISSUE TITLE
User loses permission to his own chests if he has a long name

### ISSUE THREAD

**Issue by Towelie** [md-5/Deadbolt#50]
Steps to reproduce:
1. Have a long name (in my case WWWWWWWWWWWWWWWM (15xW+1xM -> 16 chars in total)
2. Protect a chest
3. Move away from the chest, and allow the chunk to unload (i am certain this occurs when the chunk unloads, the name is truncated)
4. Return and attempt to interract with the chest

The following occurs:
The user will get an "Access Denied" error and won't be able to interract with his own chests

**Comment by Towelie** [comment]
Bump, still happens in the last R6 build

**Comment by cyberkitsune** [comment]
I can also confirm, the bug still exists.

**Comment by TerrorBite** [comment]
This appears to have been caused by 67ceba0.

**Comment by sapincher** [comment]
Has anyone verified that this has been fixed in latest release? It's a pretty serious problem that caused my server to switch back to Lockette, so hopefully we can close this issue.

**Comment by TerrorBite** [comment]
I believe it has indeed been fixed in the lastest release; if not, I have a custom build (created by [cyberkitsune](https://github.com/cyberkitsune)) that works fine.

**Comment by sapincher** [comment]
So, I tried Deadbolt again hoping this problem was fixed, but same thing - names are truncated to 13 characters and the chest protection becomes "expired," since Deadbolt can't find the last login of a user that doesn't exist. I get the message that goes something like "This chest protection has expired" even upon turning auto-expiration off, which is really silly.

Because a significant portion of my server's userbase has names that are 14+ characters, this plugin is absolutely unusable.

**Comment by JukkaTibbs** [comment]
BUMP - along with my post to the Dev.bukkit.org - Server Mods section for this plugin .....
Hallo, Tibbs here. I am expirencing maybe a problemo with the Deadbolt Vers. 2.1 With Bukkit build : git-bukkit-1.2.3-R0.2-75 in Minecraft 1.2.4 (API version 1.2.4-R0.1-Snapshot) BETA build. where the expiration runs out on locked chests after a set amount of days. that number of days is most likely the default, I have not changed anything about the Deadbolt plugin yet, At All. So if anyone else Gets this or knows how to fix I'll follow this plugin for a few days or until the next bukkit release just to try to fix this issue :] Thanksies!!! TIBBS~

**Comment by TerrorBite** [comment]
You did check the plugin's config file right? There is a configuration
option for chest expiration. It's on by default, but you can turn it
off easily.

**Comment by sapincher** [comment]
My problem persists after turning auto-expiration off, which makes this quite silly
